---
title: Quiz 2
output:
  html_document:
    css: ../styles/base.css
    highlight: null
    theme: null
    includes:
      in_header: ../styles/notebook.html
---

## Instructions

>  Write your name at the top right.  You are to work on this quiz alone without any help 
>  from any other resource <b>except for a single $8.5 \times 11$ inch page of handwritten notes</b>.  
>  This quiz will be ungraded but must be handed in for attendance. 


## Problems:

### Problem 1:
When asked to state the simple linear regression model, a student wrote it as follows: 
$$\mathbb{E}\left[Y_i\right] = \beta_0 + \beta_1 X_i + \epsilon_i$$ 
Do you agree?  Explain.
<div class="answer_div"></div>



### Problem 2:
What is the <b>BLUE</b>?  Explain in what sense this is an "optimal" regression solution, and under what conditions these properties hold true.
<div class="answer_div"></div>


<div class="pagebreak"></div>
### Problem 3:
Use the definition of the <b>unbiased, sample-based variance estimate</b> to recover the regression estimate for $\sigma^2$.
Recall, the denominator must divide by the degrees of freedom remaining after the estimation of the mean.


